nav:
  - "*.md"
  - Abilities:
     - "abilities/*.md"
  - Artifacts:
     - "artifacts/*.md"
  - Astrologers Proclaim:
     - "astrologers_proclaim/*.md"
  - Content:
     - "content/*.md"
  - Events:
     - "events/*.md"
  - Fields:
     - "fields/*.md"
  - Heroes:
     - "heroes/*.md"
  - Keywords:
     - "keywords/*.md"
     - Alternative Action: "keywords/alternative_action.md"
     - Attack: "keywords/attack_value.md"
     - Damage: "keywords/damage.md"
     - Defense: "keywords/defense_value.md"
     - Dice: "keywords/dice.md"
     - Dwelling: "keywords/dwelling.md"
     - Flying Unit: "keywords/flying_unit.md"
     - Ground Unit: "keywords/ground_unit.md"
     - Health Ponits: "keywords/health_points.md"
     - Initiative: "keywords/initiative_value.md"
     - Negative Morale: "keywords/negative_morale.md"
     - Obstacle: "keywords/obstacle.md"
     - Paralysis: "keywords/paralysis.md"
     - Permanent Effect: "keywords/permanent_effect.md"
     - Positive Morale: "keywords/positive_morale.md"
     - Ranged Unit: "keywords/ranged_unit.md"
     - Recruit: "keywords/recruit.md"
     - Reinforce: "keywords/reinforce.md"
     - Remove: "keywords/remove.md"
     - Search: "keywords/search.md"
  - Scenarios:
     - "scenarios/*.md"
  - Spels:
     - "spells/*.md"
  - Statistics:
     - "statistics/*.md"
  - Tiles:
     - "tiles/*.md"
  - Towns:
     - "towns/*.md"
  - Units:
     - "units/*.md"
  - War Machines:
     - "war_machines/*.md"
