nav:
  - "*.md"
  - Abilities:
     - "abilities/*.md"
  - Artifacts:
     - "artifacts/*.md"
  - Astrologers Proclaim:
     - "astrologers_proclaim/*.md"
  - Content:
     - "content/*.md"
  - Difficulties: "difficulties.md"
  - Events:
     - "events/*.md"
  - Fields:
     - "fields/*.md"
  - Heroes:
     - "heroes/*.md"
  - Keywords:
     - "keywords/*.md"
     - Alternative Action: "keywords/alternative_action.md"
     - Combat: "keywords/combat.md"
     - Dice: "keywords/dice.md"
     - Dwelling: "keywords/dwelling.md"
     - Empower: "keywords/empower.md"
     - Morale: "keywords/morale.md"
     - Obstacle: "keywords/obstacle.md"
     - Paralysis: "keywords/paralysis.md"
     - Permanent Effect: "keywords/permanent_effect.md"
     - Recruit: "keywords/recruit.md"
     - Reinforce: "keywords/reinforce.md"
     - Remove: "keywords/remove.md"
     - Search: "keywords/search.md"
     - Summon: "keywords/summon.md"
  - Legend: "legend.md"
  - Scenarios:
     - "scenarios/*.md"
  - Spells:
     - "spells/*.md"
  - Statistics:
     - "statistics/*.md"
  - Tiles:
     - "tiles/*.md"
  - Towns:
     - "towns/*.md"
  - Trading: "trading.md"
  - Units:
     - "units/*.md"
  - War Machines:
     - "war_machines/*.md"
